### ISSUE TITLE
Main CI fails on GridView AgentTerminalSlot prop mismatch

### ISSUE THREAD

**Issue by tangemicioglu** [wardian-app/Wardian#592]
## Problem
The `tests` workflow on `main` fails during `npm run lint` after merging #587.

Failure:

```text
src/views/GridView.tsx(402,21): error TS2322: Type '{ sessionId: string; provider: string | undefined; isMaximized: boolean; isSelected: boolean; theme: "system" | "dark" | "light"; workspacePath: string; onTerminalFocus: ((agentId: string) => void) | undefined; onTitleChange: (id: string, title: string) => void; }' is not assignable to type 'IntrinsicAttributes & AgentTerminalSlotProps'.
  Property 'isSelected' does not exist on type 'IntrinsicAttributes & AgentTerminalSlotProps'.
```

Run: https://github.com/wardian-app/Wardian/actions/runs/28150723971

## Expected
`main` should compile cleanly and preserve Grid terminal selection behavior.
